Check for Amazon in osfamilymap to create pkg repo
saltstack-formulas/prometheus-formula pull request #67
Opened 2021-07-14 00:01 UTC by mdschmitt

Fixes #65

2021-07-15 08:13 UTC, noelmcloughlin commented on prometheus/osfamilymap.yaml
> +
remove the extra lines..

2021-07-15 08:14 UTC, noelmcloughlin commented on prometheus/osfamilymap.yaml
> +        {%- set releasever = salt['cmd.run']("rpm -E '%{rhel}'") %}
Indent 4 spaces, instead of 2 spaces, to line up with the block above (suggestion, not rule).

2021-07-15 08:15 UTC, noelmcloughlin requested changes
LGTM, two suggested updates

2021-07-15 08:18 UTC, mdschmitt commented
Updated.  Not sure how those extra lines ended up in there.  Thx for pointing that and the spacing out.  Should be all good now.

2021-07-15 08:22 UTC, myii requested changes
This would be so much neater if there was an `osmap.yaml` available but that's not present unfortunately.

The testing should be updated though:

https://github.com/saltstack-formulas/prometheus-formula/blob/2c572d0019fbbac51e2a5cf70b8928496be2cae9/.gitlab-ci.yml#L170-L172

* Please comment out line 170 and then uncomment line 172, which will test both the `default` and `repo` suites for Amazon.

2021-07-16 00:15 UTC, mdschmitt commented
is `tar` ...not installed on Amazon Linux by default?  That makes no sense.

2021-07-16 00:17 UTC, mdschmitt commented
well, for the archive install, it's supposed to verify that..  I'm confused.

2021-07-16 02:19 UTC, myii commented
> is `tar` ...not installed on Amazon Linux by default? That makes no sense.

@mdschmitt This will resolve your problem.  Change the first line of this block:

https://github.com/saltstack-formulas/prometheus-formula/blob/2c572d0019fbbac51e2a5cf70b8928496be2cae9/prometheus/clientlibs/install.sls#L31-L36

To:

```diff
-        {%- if grains.get('osfinger', '') in ['Oracle Linux Server-8'] %}
+        {%- if grains.get('osfinger', '') in ['Oracle Linux Server-8', 'Amazon Linux-2'] %}
```

2021-07-16 02:24 UTC, mdschmitt commented
I'll admit, I could've found that out eventually, but I really appreciate your help.  Updated and pushed.  Thank you!

2021-07-16 02:34 UTC, mdschmitt commented
...and pipeline success!

2021-07-16 02:39 UTC, myii approved these changes

2021-07-16 02:39 UTC, merged

2021-07-16 02:40 UTC, myii commented
> I'll admit, I could've found that out eventually, but I really appreciate your help. Updated and pushed. Thank you!

@mdschmitt You're welcome.  And thank you for your excellent contribution!